### ISSUE TITLE
[ARROW-7808] Shared libraries inside jar files

### ISSUE THREAD

**Issue by Sebastiaan-Alvarez-Rodriguez** [zhztheplayer/arrow-1#1]
Hi there @zhztheplayer,

I am currently using your nice Arrow Dataset Java implementation to be able to use Datasets from Java. I can use it without problems on my own system, where I have sudo rights, have up-to-date gcc, cmake, etcetera.

However, I cannot run my jarfile, containing all dependencies, on a remote machine.
Here is the error I get on a remote machine:
```
Exception in thread "Thread-49" java.lang.NoClassDefFoundError: Could not initialize class org.apache.arrow.dataset.file.JniWrapper
	at org.apache.arrow.dataset.file.FileSystemDatasetFactory.createNative(FileSystemDatasetFactory.java:33)
	at org.apache.arrow.dataset.file.FileSystemDatasetFactory.<init>(FileSystemDatasetFactory.java:29)
	at arrow.dataset.DefaultDatasetFactory.lambda$create$0(DefaultDatasetFactory.java:49)
	at arrow.JNIMemory.withAllocatorDo(JNIMemory.scala:54)
	at arrow.dataset.DefaultDatasetFactory.create(DefaultDatasetFactory.java:48)
	at arrow.dataset.MetaDataset.dataset$lzycompute(MetaDataset.scala:34)
	at arrow.dataset.MetaDataset.dataset(MetaDataset.scala:34)
```
I want to **stress** again that the very same jar file works without problems on my local machine.

I suppose the error makes sense: I access the JniWrapper here for the very first time, so this is the first time the '.so' shared libraries are called right?

My local system has a lot more recent libraries than the server I ran on while getting this error.
My guess: *Different environments cause the .so file to fail loading propely, meaning I can use my code only on the same system I compiled this JNI bridge on.*

I noticed there was a way to compile static libraries ('.a' files) in Arrow. That might solve the problem. With '.a' files, relevant system library routines are inserted into the '.a' file,
so my server environment does not matter much then (I think).

## Questions
Here is what I would like to know:
 1. Do you think using static libraries will solve my problem?
 2. Does your JNI bridge currently support static libraries?
 3. Do you plan to add static libraries to your JNI bridge in the future?

If static libraries prove to increase independence from system libraries, I really think you should use those instead of shared libraries. Even though the library size will increase, static libs would add a piece of compatibility between systems, and Java and JARs are all about compatibility between systems.

P.S.
JNI can use static libraries since Java 8. Source: [StackOverflow](https://stackoverflow.com/questions/24493337/)

**Comment by Sebastiaan-Alvarez-Rodriguez** [comment]
After additional checking I found that
```bash
ldd libarrow_dataset_jni.so
ldd: warning: you do not have execution permission for `./libarrow_dataset_jni.so'
./libarrow_dataset_jni.so: /cm/local/apps/gcc/6.3.0/lib64/libgcc_s.so.1: version `GCC_7.0.0' not found (required by ./libarrow_dataset_jni.so)
./libarrow_dataset_jni.so: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by ./libarrow_dataset_jni.so)
./libarrow_dataset_jni.so: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./libarrow_dataset_jni.so)
./libarrow_dataset_jni.so: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./libarrow_dataset_jni.so)
./libarrow_dataset_jni.so: /cm/local/apps/gcc/6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./libarrow_dataset_jni.so)
./libarrow_dataset_jni.so: /lib64/libpthread.so.0: version `GLIBC_2.30' not found (required by ./libarrow_dataset_jni.so)
	linux-vdso.so.1 =>  (0x00002aaaaaacd000)
	libz.so.1 => /lib64/libz.so.1 (0x00002aaaabc94000)
	libstdc++.so.6 => /cm/local/apps/gcc/6.3.0/lib64/libstdc++.so.6 (0x00002aaaabeaa000)
	libm.so.6 => /lib64/libm.so.6 (0x00002aaaac22b000)
	libgcc_s.so.1 => /cm/local/apps/gcc/6.3.0/lib64/libgcc_s.so.1 (0x00002aaaac52d000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002aaaac744000)
	libc.so.6 => /lib64/libc.so.6 (0x00002aaaac960000)
	/lib64/ld-linux-x86-64.so.2 (0x00002aaaaaaab000)
```

So yeah, that's a bit awkward. Answering my own question: Using static libraries will **not** work to improve compatibility much, because libc code is never added to static libraries...

In my case, all I can do is (in order of difficulty):
 0. Spawn a VM resembling the old system, compile the library there, and pray that it works on the actual remote.
 1. Compile the library on the remote. This will be really painful, because everything on the remote is a bit dated and I have no sudo rights. So I would need to compile recent enough versions of `cmake, libboost-all-dev automake bison flex g++ git libevent-dev libssl-dev libtool make`  on the remote system without sudo.
 2. Use [musl](https://www.musl-libc.org/how.html) to compile the library, but I am not sure JNI can handle that and this is quite hardcore.
 3. Use a cursed hack to download software from apt and "install" that locally.

Of course, when not having to use one specific remote, it would be the simplest to just find a host where you have root or a remote that is up to date.

**Comment by Sebastiaan-Alvarez-Rodriguez** [comment]
What this leaves me wondering: How will you approach building releases for your code in the future?
It might make sense to add the jni-bridge shared libraries to the libarrow-dev package, and remove them from the `arrow-dataset.jar`.
That way, the `jar` becomes portable between systems (like jars should be), and users only have to install libarrow-dev for the jni bridge.

**Comment by zhztheplayer** [comment]
Hi Sebastiaan, 

I assume you encountered a dependency version problem right? E.g. try loading the library on lower version of glibc/gcc than it was built. I think you could have a try but I am not sure static linking will always work on issues like this because the dependencies are pretty low-level and tightly bounded with operation system.

I think a common practice to solve such a problem is to compile cpp files on comparatively elder Linux environment then it should be able to run on higher. It will be a little annoying in cases like yours that local machine has higher version while remote server has lower. Anyway it might be an option to install a virtual machine from local to compile the sources.

Regarding the Java library releases, AFAIK official Apache Arrow Java libraries don't do much on compatibility: I downloaded arrow-orc-2.0.0.jar and arrow-gandiva-2.0.0.jar then found the C++ libs included in the jars are `dylib`s. If I am guessing correctly users can not run it directly on Windows or Linux. I know some other opensource repositories like `lz4-java` includes multiple C++ binary files for different system types like win/osx/linux, maybe that is a feasible direction for Arrow Java releases. But so far the compatibility is still limited.

**Comment by Sebastiaan-Alvarez-Rodriguez** [comment]
Hi there, hadn't heard of `dylib`s so far, seems interesting, thanks!

Yes I spawned a VM resembling my target system, and compiled on there using su rights.
Thanks for the info!
